num1 = int(input("enter the first number : "))
num2 = int(input("enter the second number : "))
print (f"{num1} + {num2} = {num1+num2}")
print (f"{num1} - {num2} = {num1-num2}")
print (f"{num1} / {num2} = {round(num1/num2)}")
print (f"{num1} * {num2} = {num1*num2}")